CREATE OR REPLACE PACKAGE BODY maut_service 


AS PROCEDURE BERECHNEMAUT(P_MAUTABSCHNITT MAUTABSCHNITT.ABSCHNITTS_ID%TYPE, P_ACHSZAHL FAHRZEUG.ACHSEN%TYPE, P_KENNZEICHEN FAHRZEUG.KENNZEICHEN%TYPE) AS 
v_dummy integer; 
fID  FAHRZEUG.FZ_ID%TYPE;
achs  FAHRZEUG.ACHSEN%TYPE;
kz FAHRZEUG.KENNZEICHEN%TYPE;
aut BOOLEAN;
BEGIN 



SELECT f.KENNZEICHEN, f.ACHSEN
into kz, achs
FROM Fahrzeug f
WHERE f.KENNZEICHEN = P_KENNZEICHEN;

SELECT b.KENNZEICHEN into kz
FROM BUCHUNG b
WHERE b.KENNZEICHEN = P_KENNZEICHEN;

IF kz IS NOT NULL  THEN
    IF achs != P_ACHSZAHL THEN
        raise INVALID_VEHICLE_DATA;
    ELSE 
     raise INVALID_VEHICLE_DATA;

END IF;
/*
manuel
*/


END IF;

EXCEPTION 
WHEN NO_DATA_FOUND then
  raise UNKOWN_VEHICLE;
WHEN others then
   raise UNKOWN_VEHICLE;
   
        
    
            
END BERECHNEMAUT;

END maut_service;